# Generated by Django 3.2.8 on 2021-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211019_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.CharField(default='Duis vitae consequat neque. Nulla pharetra eleifend nulla', max_length=50),
        ),
    ]
